### ISSUE TITLE
pi.set_mode fails with NoneType Object

### ISSUE THREAD

**Issue by choeffer** [joan2937/pigpio#234]
Hello,

the following code throughs this error, after the while True loop sucessfully runs once:

"
{0: 26.61505, 90: 86.54184000000001, -45: 400, 45: 101.841201, -90: 175.83104}
Traceback (most recent call last):
  File "/home/pink/Dokumente/csalgori/lib_hc_sr04.py", line 221, in <module>
    ranger = scanner()
  File "/home/pink/Dokumente/csalgori/lib_hc_sr04.py", line 180, in __init__
    self.sonar = hcsr04(pi = self.pi, trigger = self.trigger, echo = self.echo)
  File "/home/pink/Dokumente/csalgori/lib_hc_sr04.py", line 20, in __init__
    self.pi.set_mode(gpio = self.trigger, mode = pigpio.OUTPUT)
  File "/home/pink/Dokumente/csalgori/venv/lib/python3.5/site-packages/pigpio.py", line 1296, in set_mode
    return _u2i(_pigpio_command(self.sl, _PI_CMD_MODES, gpio, mode))
  File "/home/pink/Dokumente/csalgori/venv/lib/python3.5/site-packages/pigpio.py", line 983, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'
"

Used code:

`
import pigpio
import time

#https://cdn.sparkfun.com/assets/b/3/0/b/a/DGCH-RED_datasheet.pdf
class hcsr04:

    def __init__(self, pi, trigger, echo, pulse_len = 15):

        self.pi = pi
        self.trigger = trigger
        self.echo = echo
        self.pulse_len = pulse_len
        self.tick_high = None
        self.tick_high_old = None
        self.tick_low = None
        self.tick_low_old = None
        self.pulse_width = None

        #http://abyz.me.uk/rpi/pigpio/python.html#set_mode
        self.pi.set_mode(gpio = self.trigger, mode = pigpio.OUTPUT)
        self.pi.set_mode(gpio = self.echo, mode = pigpio.INPUT)

        #http://abyz.me.uk/rpi/pigpio/python.html#callback
        self.cb = self.pi.callback(user_gpio=self.echo, edge=pigpio.EITHER_EDGE, func=self.cbf)

    #calculate the duty cycle
    def cbf(self, gpio, level, tick):

        #change to low (a falling edge)
        if level == 0:
            
            self.tick_low = tick
            #try is needed because one of t1 or t2 might not be an int and then tickDiff would fail
            try:
                #http://abyz.me.uk/rpi/pigpio/python.html#callback
                # tick        32 bit    The number of microseconds since boot
                #                       WARNING: this wraps around from
                #                       4294967295 to 0 roughly every 72 minutes
                #Tested: This is handled by the tickDiff function internally, if t1 (earlier tick)
                #is smaller than t2 (later tick), which could happen every 72 min. The result will
                #not be a negative value, the real difference will be properly calculated.
                self.pulse_width = pigpio.tickDiff(t1=self.tick_high, t2=tick)
            except Exception:
                pass
            
        #change to high (a rising edge)
        elif level == 1:

            self.tick_high = tick

    def trig(self):

        #default pulse_len is 50% more than needed (15 microseconds instead of 10)
        #to have a buffer to surely trigger the measurement
        self.pi.gpio_trigger(user_gpio = self.trigger, pulse_len = self.pulse_len, level = 1)

    def read(self, temp_air = 20, time_betw_trig_and_read_out = 0.368, upper_limit = 400):
        
        #implement hard reset of the while true loop with setting tick_high and tick_low to None 
        # after x rounds in the while loop to dont have an infinite loop if
        #haning of the sensor in the loop 

        #check if recognized rising and falling edges are valid, so correctly catched by the callback function
        while self.tick_high is None or self.tick_high is self.tick_high_old or self.tick_low is None or self.tick_low is self.tick_low_old or self.pulse_width is None:
            
            #sent trigger signal to the sensor
            self.trig()
            #let the sensor make the measurements, it will do a 8 cycle sonic burst
            #max distance is 4m so max measurement time for one sonic burst is:
            #400×10000×2÷343,42=23295,09 microsecond or 23 ms or 0,023 s at temp_air = 20
            #so 8 cycle sonic burst should take in worst 8 * 0,023 s = 0,184 s
            #so adding 100% buffer would lead to 0,276 s so ~ 0,368 s, which is the chosen default
            #but that also depends on the used sonar sensor, see datasheet
            #in this time frame the callback function should be called two times for each sonic burst.
            time.sleep(time_betw_trig_and_read_out)

        #and store the the last values of self.tick_high and self.tick_low
        self.tick_high_old = self.tick_high
        self.tick_low_old = self.tick_low
        #set self.tick_high and self.tick_low back to initial values
        self.tick_high = None
        self.tick_low = None

        #speed of sound at 20 degree celsius
        #c_air = 343.42 m/s, if temp = 20 degree
        c_air = 331.3 + (0.606 * temp_air)
        #calculated distance in cm
        distance = self.pulse_width / 10000 * c_air / 2

        #set self.pulse width back to initial value
        self.pulse_width = None

        #check if measured/calculated distance is out of measurement range of the sensor,
        #see datasheet
        if distance >= upper_limit:

            distance = upper_limit

        return distance
    
    def cancel(self):

        self.cb.cancel()

#https://www.parallax.com/sites/default/files/downloads/900-00005-Standard-Servo-Product-Documentation-v2.2.pdf

class standard_servo:

    def __init__(self, pi, gpio, min_pw = 1000, max_pw = 2000, min_degree = -90, max_degree = 90):

        self.pi = pi
        self.gpio = gpio
        #min_pw and max_pw might needed to be interchanged, depending on
        #if min_pw is moving servo to max_right or max_left,
        #see test functions below
        self.min_pw = min_pw
        self.max_pw = max_pw
        #allowed range of servo movement, see max_left(), max_right() functions
        self.min_degree = min_degree
        self.max_degree = max_degree

    def set_pw(self, pulse_width):
        
        #be carefully with setting the pulsewidth!!!
        #test carefully min_pw and max_pw value before settting them!!!
        #this can DAMAGE the servo!!!
        #http://abyz.me.uk/rpi/pigpio/python.html#set_servo_pulsewidth
        if self.min_pw <= pulse_width <= self.max_pw:

            self.pi.set_servo_pulsewidth(user_gpio = self.gpio, pulsewidth = pulse_width)
        
    def calc_pw(self, degree = 0):

        #calculate slope for calculating the pulse width
        slope = (self.min_pw - ((self.min_pw + self.max_pw)/2)) / self.max_degree

        pulse_width = slope * degree + ((self.min_pw + self.max_pw)/2)
        
        return pulse_width

    def set_position(self, degree = 0):

        if self.min_degree <= degree <= self.max_degree:

            calculated_pw = self.calc_pw(degree = degree)
            self.set_pw(pulse_width = calculated_pw)

    def middle_position(self):

        #defines 0 degree
        pulse_width = (self.min_pw+self.max_pw)/2
        self.set_pw(pulse_width = pulse_width)

    def max_left(self):
        
        #defines -90 degree
        self.set_pw(self.max_pw)

    def max_right(self):

        #defines +90 degree
        self.set_pw(self.min_pw)

class scanner:

    #default values are for the CS installation used
    def __init__(self, pi = pigpio.pi(), trigger = 6, echo = 5, gpio = 22, min_pw = 600, max_pw = 2350, angles = [-90, -45, 0, 45, 90]):

        #create one pigpio.pi() instance for the sensor and servo in parallel     
        self.pi = pi
        self.trigger = trigger
        self.echo = echo
        self.gpio = gpio
        self.min_pw = min_pw
        self.max_pw = max_pw
        self.angles = angles

        #initialize sonar and servo instance
        #https://gpiozero.readthedocs.io/en/stable/recipes.html#pin-numbering
        self.sonar = hcsr04(pi = self.pi, trigger = self.trigger, echo = self.echo)
        self.servo = standard_servo(pi = self.pi, gpio = self.gpio, min_pw = self.min_pw, max_pw = self.max_pw)

        #buffer time for initializing everything
        time.sleep(1)

    def read_all_angles(self):

        #create an empty dict
        measurement_dict = dict()
        #return servo to middle position, to not have to move e.g. from
        #last 90 degree to new -90 degree in following for loop
        self.servo.middle_position()
        time.sleep(1)

        for ang in self.angles:

            self.servo.set_position(degree = ang)
            time.sleep(1)
            measurement_dict[ang] = self.sonar.read()
        
        return measurement_dict

    def cancel(self):

        #http://abyz.me.uk/rpi/pigpio/python.html#callback
        self.sonar.cancel()
        #http://abyz.me.uk/rpi/pigpio/python.html#stop
        self.pi.stop()

if __name__ == '__main__':

    #### Example 1
    # ranger = scanner()
    # distances = ranger.read_all_angles()
    # print(distances)
    # #invoking this in the end is important
    # ranger.cancel()

    #### Burn in test
    while True:
        ranger = scanner()
        distances = ranger.read_all_angles()
        print(distances)
        #invoking this in the end is important
        ranger.cancel()
        time.sleep(2)

    #### Example 2
    # pi = pigpio.pi()
    # servo = standard_servo(gpio = 22, pi = pi, min_pw = 600, max_pw = 2350)
    # servo.middle_position()
    # time.sleep(1)
    # servo.max_right()
    # time.sleep(1)
    # servo.set_position(degree = 45)
    # pi.stop()

`

If running the code like the following and not like the code example, so not every time initialize an instance and then also cancel it at the end,
"
ranger = scanner()
while True:
        distances = ranger.read_all_angles()
        print(distances)

#invoking this in the end is important
ranger.cancel()
"
the while True loop was functioning without any problem for at least 15 min.

**Comment by choeffer** [comment]
```
    #### Burn in test
    while True:
        ranger = scanner(pi = pigpio.pi())
        distances = ranger.read_all_angles()
        print(distances)
        #invoking this in the end is important
        ranger.cancel()
        time.sleep(2)
```

solved the problem. So it was an issue on my side I think.
Seems that just the first time the class is created with "ranger = scanner()" a pigpio.pi() object is created, and after a pi.stop() "ranger.cancel()" a new instance of the class will not get created properly if not explicitly called again.
