### ISSUE TITLE
DHT11 Example code

### ISSUE THREAD

**Issue by joan2937** [joan2937/pigpio#5]
I received a message as follows.

I've pulled up the python script dht11.py in the EXAMPLES directory and ran it with a DHT11 attached to the gpio as described in the online manuals. After reformatting the Print statement to list the Temp and Rel Humid on one line, what I get is:

> ================================ RESTART ================================
> 
> T: 0 C, RH: 0 %
> T: 0 C, RH: 0 %
> T: 0 C, RH: 0 %
> T: 0 C, RH: 0 %

> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner self.run()
> File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 868, in run cb.func(cb.gpio, newLevel, 
> tick)
> File "/home/pi/pigpio/EXAMPLES/Python/DHT11_SENSOR/dht11.py", line 69, in 
> either_edge_callback handler(tick, diff)
> File "/home/pi/pigpio/EXAMPLES/Python/DHT11_SENSOR/dht11.py", line 91, in _edge_RISE
> raise
> TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

> T: 25 C, RH: 36 %
> T: 25 C, RH: 36 %
> T: 25 C, RH: 36 %
> T: 25 C, RH: 36 %

=== I hit CTRL-C to kill it ===

So, the code returns 0's for Temperature and Humidity until it hits some exception and then it starts getting and listing the reasonable (actual?) values. Any idea what is going wrong at the start? Sometimes it gives 0's for quite awhile before it hits the exception and starts giving real values. Other times it will stay at T=0, but return low humidity values like 1% or 5% and continues on without hitting the exception, but this is much less common.

I will have a look at the problem but can't commit to a time-scale.

**Comment by joan2937** [comment]
I have just got a DHT11 so can use the code.  It works fine with Python2 but does not work with Python3.  I'll assume this is by design.

I have had no other reports of errors so am closing this issue.
